# Path to your Oh My Zsh installation.
export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME=""
plugins=(git zsh-autosuggestions zsh-autocomplete)
source $ZSH/oh-my-zsh.sh

export EDITOR='nvim'

# TODO : create aliases

# pyenv import
export PYENV_ROOT="$HOME/.pyenv"
[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"

# starship import
eval "$(starship init zsh)"

